services:
  - type: web
    name: pimp-da-file
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
